#ifndef OS_SPEC_CFG_H_
#define OS_SPEC_CFG_H_


#define OSSPEC_USE_MUTEX
#define OSSPEC_USE_EVENTS
#define OSSPEC_USE_THREADS


#define OSSPEC_ERR_MUTEX_INVALID_HANDLE     -1
#define OSSPEC_ERR_MUTEX_LOCK_TOUT          -2
#define OSSPEC_ERR_MUTEX_RELEASE            -3


#define OSSPEC_ERR_EVENT_INVALID_HANDLE     OSSPEC_ERR_MUTEX_INVALID_HANDLE
#define OSSPEC_ERR_EVENT_WAIT_TOUT          OSSPEC_ERR_MUTEX_LOCK_TOUT


#define OSSPEC_ERR_THREAD_INVALID_HANDLE    OSSPEC_ERR_MUTEX_INVALID_HANDLE
#define OSSPEC_ERR_THREAD_WAIT_TOUT         OSSPEC_ERR_MUTEX_LOCK_TOUT




#endif
